---
title: "qpToolkit General Purpose Functions"
author: "Klaas Prins"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette

vignette: >
  %\VignetteIndexEntry{qpToolkit General Purpose Functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, echo=F, results='hide',message=F,warning=F}
library(qpToolkit)
```

Kick off by creating some play data with PK and PD data.

```{r}
pkpdData = example.pkpdData()
```

```{r}
example("extract.number")
example("extract.character")
example("cut3")
example("geomean")
example("expand.data")
example("geomean.smedian.hilow")
example("formatted.signif")
example("fxs")
example("insert.blanks")
example("isNumeric")
example("asNumeric")
example("locf")
example("miss.col")
example("orderedNumeric")
example("reorder.names")
example("repeath.nth")
example("sample.by.id")
example("rnorm.by.id")
example("shuffle.list")
example("swap")
example("tabulate.samples")
example("trimSpace")
```

## functions with graphs
```{r, fig.width=7, fig.height=7}
example("logit.inv")
example("unitDensity")
example("unitHistogram")
example("rgenpois")
example("boxcoxf")
example("doubleStack")
```

## functions with graphs
```{r, fig.width=7, fig.height=7}
example("logit.inv")
example("unitDensity")
example("unitHistogram")
example("rgenpois")
example("boxcoxf")
example("doubleStack")
```

